#!/bin/sh


bspc monitor -d I II III IV V VI VII VIII IX X

bspc config top_padding 		16
bspc config border_width        2
bspc config window_gap          12
bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Gcolor3 floating=true center=true
bspc rule -a Java floating=true center=true
bspc rule -a Lxappearance floating=true center=true
bspc rule -a Pavucontrol floating=true center=true
bspc rule -a Stardict floating=true center=true
bspc rule -a Zenity floating=true center=true
bspc rule -a mpv floating=true center=true
#bspc rule -a Firefox desktop=^1 follow=true
#bspc rule -a ranger desktop=^2
#bspc rule -a GuitarPro desktop=^3 follow=true
#bspc rule -a Lingot desktop=^3 follow=true floating=true
#bspc rule -a music desktop=^3 follow=true
#bspc rule -a irc desktop=^4
#bspc rule -a mutt desktop=^4
#bspc rule -a Gimp desktop=^5 follow=true

xsetroot -cursor_name left_ptr &

panel &

